import csv

data = [
    ["Supermercado", "Categoria", "Subcategoria", "Subseccion"],

    # Viví Saludable
    ["Disco", "Viví Saludable", "", ""],

    # Ofertas
    ["Disco", "Ofertas", "Ofertas de fin de semana", "Hasta 35% en Almacén y Bebidas"],
    ["Disco", "Ofertas", "Ofertas de fin de semana", "Hasta 2do al 80% en Perfumería y Limpieza"],
    ["Disco", "Ofertas", "Ofertas de fin de semana", "Hasta 2do al 50% en Frescos y Lácteos"],
    ["Disco", "Ofertas", "Electrodomésticos", "Hasta 30% + Hasta 12 CSI en Calefacción seleccionada"],
    ["Disco", "Ofertas", "Electrodomésticos", "Hasta 20% + Hasta 12 CSI en Heladeras, Lavarropas, Microondas y más"],
    ["Disco", "Ofertas", "Electrodomésticos", "Hasta 35% + Hasta 12 CSI Notebooks, Tablets, Audio y más"],
    ["Disco", "Ofertas", "Electrodomésticos", "Hasta 30% en Pequeños Electrodomésticos"],
    ["Disco", "Ofertas", "Electrodomésticos", "15% + 12 CSI en TV y Celulares"],

    # Electro
    ["Disco", "Electro", "Aire Acondicionado y Ventilación", "Aire Acondicionado"],
    ["Disco", "Electro", "Aire Acondicionado y Ventilación", "Ventilación"],
    ["Disco", "Electro", "Audio", "Calefacción"],
    ["Disco", "Electro", "Audio", "Calefones"],
    ["Disco", "Electro", "Audio", "Termotanques"],
    ["Disco", "Electro", "Cocinas y Hornos", "Anafes"],
    ["Disco", "Electro", "Cocinas y Hornos", "Cocinas"],
    ["Disco", "Electro", "Cocinas y Hornos", "Hornos"],
    ["Disco", "Electro", "Cocinas y Hornos", "Microondas"],
    ["Disco", "Electro", "Cocinas y Hornos", "Purificadores"],
    ["Disco", "Electro", "Consolas y Videojuegos", "Consolas"],
    ["Disco", "Electro", "Consolas y Videojuegos", "Videojuegos"],
    ["Disco", "Electro", "Heladeras, Freezers y Cavas", "Heladera No Frost"],
    ["Disco", "Electro", "Heladeras, Freezers y Cavas", "Heladera Cíclica"],
    ["Disco", "Electro", "Heladeras, Freezers y Cavas", "Freezers"],
    ["Disco", "Electro", "Heladeras, Freezers y Cavas", "Heladeras Cavas"],
    ["Disco", "Electro", "Informática", ""],
    ["Disco", "Electro", "Lavado", "Lavarropas"],
    ["Disco", "Electro", "Lavado", "Secarropas"],
    ["Disco", "Electro", "Lavado", "Lavavajillas"],
    ["Disco", "Electro", "Pequeños Electros", "Procesadoras"],
    ["Disco", "Electro", "Pequeños Electros", "Licuadoras"],
    ["Disco", "Electro", "Pequeños Electros", "Aspiradoras"],
    ["Disco", "Electro", "Pequeños Electros", "Batidoras"],
    ["Disco", "Electro", "Pequeños Electros", "Cuidado Personal"],
    ["Disco", "Electro", "Pequeños Electros", "Pequeños Electros de Cocina"],
    ["Disco", "Electro", "Pequeños Electros", "Pequeños Electros de Hogar"],
    ["Disco", "Electro", "Pequeños Electros", "Salud"],
    ["Disco", "Electro", "Pequeños Electros", "Cafeteras y Molinillos"],
    ["Disco", "Electro", "Teléfonos", "Celulares"],
    ["Disco", "Electro", "Teléfonos", "Accesorios"],
    ["Disco", "Electro", "TV y Video", "Televisores"],
    ["Disco", "Electro", "TV y Video", "Accesorios"],

    # Tiempo Libre
    ["Disco", "Tiempo Libre", "Aire Libre", ""],
    ["Disco", "Tiempo Libre", "Automotor", "Accesorios para el Auto"],
    ["Disco", "Tiempo Libre", "Automotor", "Cubiertas"],
    ["Disco", "Tiempo Libre", "Automotor", "Limpieza"],
    ["Disco", "Tiempo Libre", "Automotor", "Lubricantes y Refrigerantes"],
    ["Disco", "Tiempo Libre", "Automotor", "Repuestos"],
    ["Disco", "Tiempo Libre", "Suplementos", ""],
    ["Disco", "Tiempo Libre", "Paraguas", ""],
    ["Disco", "Tiempo Libre", "Juguetería", "Ensamblajes y Rompecabezas"],
    ["Disco", "Tiempo Libre", "Juguetería", "Juegos de Mesa"],
    ["Disco", "Tiempo Libre", "Juguetería", "Juguetes de Playa y Agua"],
    ["Disco", "Tiempo Libre", "Juguetería", "Juguetes para Bebés"],
    ["Disco", "Tiempo Libre", "Juguetería", "Juguetes"],
    ["Disco", "Tiempo Libre", "Juguetería", "Muñecas y Muñecos"],
    ["Disco", "Tiempo Libre", "Juguetería", "Peluches"],
    ["Disco", "Tiempo Libre", "Juguetería", "Disfraces"],
    ["Disco", "Tiempo Libre", "Juguetería", "Vehículos y Pistas"],
    ["Disco", "Tiempo Libre", "Valijas, Bolsos, Mochilas y Luncheras", ""],
    ["Disco", "Tiempo Libre", "Librería", "Libros"],

    # Almacén
    ["Disco", "Almacén", "Aceites y Vinagres", "Aceites Comunes"],
    ["Disco", "Almacén", "Aceites y Vinagres", "Aceites Especiales"],
    ["Disco", "Almacén", "Aceites y Vinagres", "Acetos"],
    ["Disco", "Almacén", "Aceites y Vinagres", "Jugos de Limón"],
    ["Disco", "Almacén", "Aceites y Vinagres", "Vinagres"],
    ["Disco", "Almacén", "Aderezos", "Mayonesas"],
    ["Disco", "Almacén", "Aderezos", "Ketchup"],
    ["Disco", "Almacén", "Aderezos", "Mostazas"],
    ["Disco", "Almacén", "Aderezos", "Salsas Golf"],
    ["Disco", "Almacén", "Aderezos", "Salsas Frías"],
    ["Disco", "Almacén", "Aderezos", "Otros Condimentos"],
    ["Disco", "Almacén", "Arroz y Legumbres", "Arroz"],
    ["Disco", "Almacén", "Arroz y Legumbres", "Arroz Listos"],
    ["Disco", "Almacén", "Arroz y Legumbres", "Legumbres"],
    ["Disco", "Almacén", "Arroz y Legumbres", "Sal"],
    ["Disco", "Almacén", "Arroz y Legumbres", "Sal, Pimienta y Especias"],
    ["Disco", "Almacén", "Arroz y Legumbres", "Especias"],
    ["Disco", "Almacén", "Conservas", "Conservas de Carne"],
    ["Disco", "Almacén", "Conservas", "Conservas de Frutas"],
    ["Disco", "Almacén", "Conservas", "Conservas de Pescado"],
    ["Disco", "Almacén", "Conservas", "Conservas de Verduras y Legumbres"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Azúcar y Edulcorantes"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Bizcochuelos, Budines y Magdalenas"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Cacao y Saborizantes"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Cafés"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Cereales"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Galletas Dulces"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Galletitas Saladas"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Leches"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Mermeladas y Jaleas"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Piononos"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Tés"],
    ["Disco", "Almacén", "Desayuno y Merienda", "Yerbas"],
    ["Disco", "Almacén", "Golosinas y Chocolates", "Alfajores"],
    ["Disco", "Almacén", "Golosinas y Chocolates", "Bocaditos y Postres"],
    ["Disco", "Almacén", "Golosinas y Chocolates", "Bombones"],
    ["Disco", "Almacén", "Golosinas y Chocolates", "Caramelos y Chicles"],
    ["Disco", "Almacén", "Golosinas y Chocolates", "Chocolates"],
    ["Disco", "Almacén", "Golosinas y Chocolates", "Turrones y Grageas"],
    ["Disco", "Almacén", "Harinas", "Harinas"],
    ["Disco", "Almacén", "Harinas", "Avenas y Sémolas"],
    ["Disco", "Almacén", "Panificados", "Lacteados"],
    ["Disco", "Almacén", "Panificados", "Pan Para Hamburguesas y Panchos"],
    ["Disco", "Almacén", "Panificados", "Tostadas y Grisines"],
    ["Disco", "Almacén", "Panificados", "Pan Rallado y Rebozador"],
    ["Disco", "Almacén", "Panificados", "Integral y Salvado"],
    ["Disco", "Almacén", "Sopas, Caldos y Puré", "Puré"],
    ["Disco", "Almacén", "Sopas, Caldos y Puré", "Sopas"],
    ["Disco", "Almacén", "Sopas, Caldos y Puré", "Caldos"],
    ["Disco", "Almacén", "Para Preparar", "Bizcochuelos, Brownies y Tortas"],
    ["Disco", "Almacén", "Para Preparar", "Comidas"],
    ["Disco", "Almacén", "Para Preparar", "Flanes"],
    ["Disco", "Almacén", "Para Preparar", "Gelatinas"],
    ["Disco", "Almacén", "Para Preparar", "Helados"],
    ["Disco", "Almacén", "Para Preparar", "Mousse"],
    ["Disco", "Almacén", "Para Preparar", "Postres"],
    ["Disco", "Almacén", "Para Preparar", "Snacks"],
    ["Disco", "Almacén", "Pastas Secas y Salsas", "Pastas Secas Guiseras"],
    ["Disco", "Almacén", "Pastas Secas y Salsas", "Pastas Secas Largas"],
    ["Disco", "Almacén", "Pastas Secas y Salsas", "Pastas Listas"],
    ["Disco", "Almacén", "Pastas Secas y Salsas", "Salsas"],
    ["Disco", "Almacén", "Snacks", "Frutas Secas y Disecadas"],
    ["Disco", "Almacén", "Snacks", "Maní"],
    ["Disco", "Almacén", "Snacks", "Nachos"],
    ["Disco", "Almacén", "Snacks", "Palitos de Maíz"],
    ["Disco", "Almacén", "Snacks", "Palitos Salados"],
    ["Disco", "Almacén", "Snacks", "Papas Fritas"],
    ["Disco", "Almacén", "Snacks", "Pochoclos"],
    ["Disco", "Almacén", "Snacks", "Snacks"],

    # Bebidas
    ["Disco", "Bebidas", "A Base de Hierbas", ""],
    ["Disco", "Bebidas", "Aguas", "Aguas Sin Gas"],
    ["Disco", "Bebidas", "Aguas", "Aguas Con Gas"],
    ["Disco", "Bebidas", "Aguas", "Aguas Saborizadas"],
    ["Disco", "Bebidas", "Aperitivos", ""],
    ["Disco", "Bebidas", "Bebidas Blancas", ""],
    ["Disco", "Bebidas", "Cervezas", ""],
    ["Disco", "Bebidas", "Champagnes", ""],
    ["Disco", "Bebidas", "Energizantes", ""],
    ["Disco", "Bebidas", "Gaseosas", "Cola"],
    ["Disco", "Bebidas", "Gaseosas", "Lima Limón"],
    ["Disco", "Bebidas", "Gaseosas", "Naranja"],
    ["Disco", "Bebidas", "Gaseosas", "Pomelo"],
    ["Disco", "Bebidas", "Gaseosas", "Tónica"],
    ["Disco", "Bebidas", "Gaseosas", "Guaraná"],
    ["Disco", "Bebidas", "Generosos", ""],
    ["Disco", "Bebidas", "Hielo", ""],
    ["Disco", "Bebidas", "Isotónicas", ""],
    ["Disco", "Bebidas", "Jugos", "En Polvo"],
    ["Disco", "Bebidas", "Jugos", "Listos"],
    ["Disco", "Bebidas", "Jugos", "Granadina"],
    ["Disco", "Bebidas", "Jugos", "Frescos"],
    ["Disco", "Bebidas", "Licores", ""],
    ["Disco", "Bebidas", "Sidras", ""],
    ["Disco", "Bebidas", "Vinos", "Vinos Blancos"],
    ["Disco", "Bebidas", "Vinos", "Vinos Tintos"],
    ["Disco", "Bebidas", "Vinos", "Vinos Rosados"],
    ["Disco", "Bebidas", "Vinos", "Vinos Frizantes"],
    ["Disco", "Bebidas", "Whiskys", ""],

    # Carnes
    ["Disco", "Carnes", "Carne Vacuna", "Novillito"],
    ["Disco", "Carnes", "Carne Vacuna", "Novillito Especial"],
    ["Disco", "Carnes", "Carne Vacuna", "La Hacienda Premium"],
    ["Disco", "Carnes", "Carne de Cerdo", ""],
    ["Disco", "Carnes", "Cordero, Lechón, Chivito y Conejo", ""],
    ["Disco", "Carnes", "Carbón y Leña", ""],
    ["Disco", "Carnes", "Listos Para Cocinar", ""],
    ["Disco", "Carnes", "Embutidos", "Chorizos"],
    ["Disco", "Carnes", "Embutidos", "Morcilla"],
    ["Disco", "Carnes", "Embutidos", "Salchichas"],
    ["Disco", "Carnes", "Pollos", ""],
    ["Disco", "Carnes", "Menudencias", ""],

    # Frutas y Verduras
    ["Disco", "Frutas y Verduras", "Frutas", "Frutas Empaquetadas"],
    ["Disco", "Frutas y Verduras", "Frutas", "Frutas Secas y Desecadas"],
    ["Disco", "Frutas y Verduras", "Frutas", "Frutas Sueltas"],
    ["Disco", "Frutas y Verduras", "Frutas", "Frutas Congeladas"],
    ["Disco", "Frutas y Verduras", "Hierbas Aromáticas y Plantines", ""],
    ["Disco", "Frutas y Verduras", "Huevos", ""],
    ["Disco", "Frutas y Verduras", "Legumbres, Granos y Semillas", ""],
    ["Disco", "Frutas y Verduras", "Orgánicos", ""],
    ["Disco", "Frutas y Verduras", "Verduras", "Hortalizas Livianas"],
    ["Disco", "Frutas y Verduras", "Verduras", "Hortalizas Pesadas"],
    ["Disco", "Frutas y Verduras", "Verduras", "Verduras Empaquetadas"],
    ["Disco", "Frutas y Verduras", "Verduras", "Verduras Frescas de Hoja"],
    ["Disco", "Frutas y Verduras", "Verduras", "Verduras Procesadas y Ensaladas Listas"],
    ["Disco", "Frutas y Verduras", "Verduras", "Verduras Secas y Desecadas"],

    # Lácteos
    ["Disco", "Lácteos", "Cremas", ""],
    ["Disco", "Lácteos", "Dulce de Leche", ""],
    ["Disco", "Lácteos", "Leches", "Leches Larga Vida"],
    ["Disco", "Lácteos", "Leches", "Leches Refrigeradas"],
    ["Disco", "Lácteos", "Leches", "Leches Saborizadas"],
    ["Disco", "Lácteos", "Leches", "Bebidas Vegetales"],
    ["Disco", "Lácteos", "Mantecas y Margarinas", "Manteca"],
    ["Disco", "Lácteos", "Mantecas y Margarinas", "Margarinas"],
    ["Disco", "Lácteos", "Pastas y Tapas", "Fideos y Ñoquis"],
    ["Disco", "Lácteos", "Pastas y Tapas", "Grasas"],
    ["Disco", "Lácteos", "Pastas y Tapas", "Masas y Levaduras"],
    ["Disco", "Lácteos", "Pastas y Tapas", "Pastas Rellenas"],
    ["Disco", "Lácteos", "Pastas y Tapas", "Tapas"],
    ["Disco", "Lácteos", "Postres", ""],
    ["Disco", "Lácteos", "Yogures", "Yogures Descremados"],
    ["Disco", "Lácteos", "Yogures", "Yogures Enteros"],

    # Perfumería
    ["Disco", "Perfumería", "Cuidado Capilar", "Coloración"],
    ["Disco", "Perfumería", "Cuidado Capilar", "Acondicionador"],
    ["Disco", "Perfumería", "Cuidado Capilar", "Fijación"],
    ["Disco", "Perfumería", "Cuidado Capilar", "Pediculosis"],
    ["Disco", "Perfumería", "Cuidado Capilar", "Reparación y Tratamientos"],
    ["Disco", "Perfumería", "Cuidado Capilar", "Shampoo"],
    ["Disco", "Perfumería", "Cuidado Capilar", "Cepillos para Pelo"],
    ["Disco", "Perfumería", "Cuidado de la Piel", "Cremas Corporales"],
    ["Disco", "Perfumería", "Cuidado de la Piel", "Cremas Desmaquillantes"],
    ["Disco", "Perfumería", "Cuidado de la Piel", "Cremas Faciales"],
    ["Disco", "Perfumería", "Cuidado de la Piel", "Solares y Post-Solares"],
    ["Disco", "Perfumería", "Cuidado Personal", "Cepillos y Esponjas"],
    ["Disco", "Perfumería", "Cuidado Personal", "Depilación"],
    ["Disco", "Perfumería", "Cuidado Personal", "Desodorantes de Hombres"],
    ["Disco", "Perfumería", "Cuidado Personal", "Desodorantes de Mujer"],
    ["Disco", "Perfumería", "Cuidado Personal", "Desodorantes y Polvos Pédicos"],
    ["Disco", "Perfumería", "Cuidado Personal", "Geles de Ducha"],
    ["Disco", "Perfumería", "Cuidado Personal", "Jabones"],
    ["Disco", "Perfumería", "Cuidado Personal", "Protección Adultos"],
    ["Disco", "Perfumería", "Cuidado Personal", "Protección Femenina"],
    ["Disco", "Perfumería", "Cuidado Personal", "Productos Para Afeitarse"],
    ["Disco", "Perfumería", "Cuidado Personal", "Quitaesmaltes"],
    ["Disco", "Perfumería", "Cuidado Personal", "Higiene Preventiva"],
    ["Disco", "Perfumería", "Cuidado Oral", "Pastas Dentales"],
    ["Disco", "Perfumería", "Cuidado Oral", "Cepillos Dentales"],
    ["Disco", "Perfumería", "Cuidado Oral", "Enjuagues Bucales"],
    ["Disco", "Perfumería", "Cuidado Oral", "Accesorios Dentales"],
    ["Disco", "Perfumería", "Farmacia", "Algodón"],
    ["Disco", "Perfumería", "Farmacia", "Alcohol"],
    ["Disco", "Perfumería", "Farmacia", "Apósitos"],
    ["Disco", "Perfumería", "Farmacia", "Preservativos"],
    ["Disco", "Perfumería", "Farmacia", "Otros"],

    # Bebés y Niños
    ["Disco", "Bebés y Niños", "Alimentación", ""],
    ["Disco", "Bebés y Niños", "Cuidado del Bebé", ""],
    ["Disco", "Bebés y Niños", "Pijamas", ""],
    ["Disco", "Bebés y Niños", "Cochecitos, Butacas y Sillitas", ""],

    # Limpieza
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Baldes y Mopas"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Bolsas"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Broches y Ganchos"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Escobas y Escobillones"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Escobillas"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Esponjas y Guantes"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Palas y Cabos"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Pañ os Multiusos"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Secadores y Cepillos"],
    ["Disco", "Limpieza", "Accesorios de Limpieza", "Trapos de Piso"],
    ["Disco", "Limpieza", "Calzado", "Brillos y Revividores"],
    ["Disco", "Limpieza", "Calzado", "Limpiadores"],
    ["Disco", "Limpieza", "Calzado", "Pomadas Para Calzado"],
    ["Disco", "Limpieza", "Desodorantes de Ambiente", "Absorbe Humedad"],
    ["Disco", "Limpieza", "Desodorantes de Ambiente", "Aromatizantes"],
    ["Disco", "Limpieza", "Desodorantes de Ambiente", "Desodorantes y Desinfectantes"],
    ["Disco", "Limpieza", "Insecticidas", "Aerosoles"],
    ["Disco", "Limpieza", "Insecticidas", "Aparatos"],
    ["Disco", "Limpieza", "Insecticidas", "Cebos, Boilillas y Pastillas"],
    ["Disco", "Limpieza", "Insecticidas", "Escobas y Escobillones"],
    ["Disco", "Limpieza", "Insecticidas", "Tabletas y Difusores"],
    ["Disco", "Limpieza", "Insecticidas", "Repelentes"],
    ["Disco", "Limpieza", "Lavandina", ""],
    ["Disco", "Limpieza", "Limpieza de Baño", "Desinfectantes"],
    ["Disco", "Limpieza", "Limpieza de Baño", "Destapa Cañerías"],
    ["Disco", "Limpieza", "Limpieza de Baño", "Pastillas y Bloques"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Aprestos y Blanqueadores"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Cepillo Para Ropa"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Jabón en Pan"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Detergente Para Ropa"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Quitamanchas"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Suavizantes"],
    ["Disco", "Limpieza", "Cuidado Para La Ropa", "Perfumantes"],
    ["Disco", "Limpieza", "Limpieza de Cocina", "Detergentes"],
    ["Disco", "Limpieza", "Limpieza de Cocina", "Escarbadientes"],
    ["Disco", "Limpieza", "Limpieza de Cocina", "Fósforos"],
    ["Disco", "Limpieza", "Limpieza de Cocina", "Limpiadores"],
    ["Disco", "Limpieza", "Limpieza de Cocina", "Limpiavidrios"],
    ["Disco", "Limpieza", "Limpieza de Cocina", "Productos Para Lavavajillas"],
    ["Disco", "Limpieza", "Limpieza de Pisos y Muebles", "Ceras y Autobrillos"],
    ["Disco", "Limpieza", "Limpieza de Pisos y Muebles", "Limpiadores de Pisos"],
    ["Disco", "Limpieza", "Limpieza de Pisos y Muebles", "Lustramuebles"],
    ["Disco", "Limpieza", "Papeles", "Pañuelos"],
    ["Disco", "Limpieza", "Papeles", "Papel Higiénico"],
    ["Disco", "Limpieza", "Papeles", "Rollos de Cocina"],
    ["Disco", "Limpieza", "Papeles", "Servilletas"],

    # Quesos y Fiambres
    ["Disco", "Quesos y Fiambres", "Quesos", "Quesos Untables"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Queso Muzzarella"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Quesos Port Salut y Cremosos"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Quesos Semiblandos"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Quesos Duros"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Quesos Especiales e Importados"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Quesos Rallados"],
    ["Disco", "Quesos y Fiambres", "Quesos", "Ricota"],
    ["Disco", "Quesos y Fiambres", "Fiambres", "Jamón Cocido y Crudo"],
    ["Disco", "Quesos y Fiambres", "Fiambres", "Fiambres"],
    ["Disco", "Quesos y Fiambres", "Dulces", ""],
    ["Disco", "Quesos y Fiambres", "Encurtidos, Aceitunas y Pickles", ""],
    ["Disco", "Quesos y Fiambres", "Salchichas", ""],

    # Congelados
    ["Disco", "Congelados", "Comidas Congeladas", "Pizzas"],
    ["Disco", "Congelados", "Comidas Congeladas", "Empanadas y Tartas"],
    ["Disco", "Congelados", "Comidas Congeladas", "Comidas Congeladas"],
    ["Disco", "Congelados", "Frutas", ""],
    ["Disco", "Congelados", "Hamburguesas y Milanesas", ""],
    ["Disco", "Congelados", "Helados y Postres", ""],
    ["Disco", "Congelados", "Papas", ""],
    ["Disco", "Congelados", "Pescados y Mariscos", ""],
    ["Disco", "Congelados", "Pollo y Carnes", ""],
    ["Disco", "Congelados", "Vegetales", ""],

    # Panadería y Repostería
    ["Disco", "Panadería y Repostería", "Panadería Salada", "Panificados"],
    ["Disco", "Panadería y Repostería", "Panadería Salada", "Pizzas y Focaccias"],
    ["Disco", "Panadería y Repostería", "Panadería Salada", "Sandwiches de Miga"],
    ["Disco", "Panadería y Repostería", "Pastelería", ""],

    # Rotisería
    ["Disco", "Rotisería", "", "Entradas"],
    ["Disco", "Rotisería", "", "Platos Principales"],
    ["Disco", "Rotisería", "", "Postres"],

    # Mascotas
    ["Disco", "Mascotas", "Accesorios para Mascotas", ""],
    ["Disco", "Mascotas", "Gatos", "Secos"],
    ["Disco", "Mascotas", "Gatos", "Húmedos"],
    ["Disco", "Mascotas", "Perros", "Secos"],
    ["Disco", "Mascotas", "Perros", "Húmedos"],

    # Hogar y Textil
    ["Disco", "Hogar y Textil", "Automotor", ""],
    ["Disco", "Hogar y Textil", "Baño", ""],
    ["Disco", "Hogar y Textil", "Cocina", ""],
    ["Disco", "Hogar y Textil", "Colchones y Almohadas", ""],
    ["Disco", "Hogar y Textil", "Decoración", ""],
    ["Disco", "Hogar y Textil", "Cotillón", ""],
    ["Disco", "Hogar y Textil", "Ferretería", ""],
    ["Disco", "Hogar y Textil", "Indumentaria", ""],
    ["Disco", "Hogar y Textil", "Mesa", ""],
    ["Disco", "Hogar y Textil", "Muebles", ""],
    ["Disco", "Hogar y Textil", "Organización", ""],
    ["Disco", "Hogar y Textil", "Ropa de Cama", ""],
]

with open("disco_menu_completo_todas_categorias.csv", "w", newline='', encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerows(data)

print("Archivo disco_menu_completo_todas_categorias.csv generado correctamente.")
print(f"Total de filas: {len(data)}")
print(f"Total de categorías (sin header): {len(data)-1}")